accepted = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib", "Unicode-3.0", "Unlicense", "CC0-1.0", "OpenSSL", "CDLA-Permissive-2.0"]
private = { ignore = true }
ignore-dev-dependencies = true
ignore-build-dependencies = true
