#pragma once

#include <functional>

#include "engine/assets/StringTable.h"
#include "engine/core/Types.h"

#include "game/config/GameConfig.h"
#include "game/menu/ControlSettings.h"
#include "game/menu/OptionMenu.h"
#include "game/menu/VideoSettings.h"

namespace gdl::game {

/** Shared title/pause settings with transactional edits. */
class SettingsMenu {
public:
    enum class Page : u8 {
        Root,
        Audio,
        Game,
        Compass,
        Difficulty,
        Multiplayer,
        Graphics,
        Controls
    };
    enum class Scope : u8 { Title, Tower, Level };
    using Persist = std::function<bool(const GameConfig&)>;
    using PreviewAudio = std::function<void(const AudioConfig&)>;
    void open(const GameConfig& config, const StringTable* strings, Persist persist,
              const TextPainter& painter, const MenuScreen& screen, MenuDefinition backdrop,
              Scope scope = Scope::Title, PreviewAudio preview = {}, DisplayOptions display = {},
              std::function<DisplayOptions()> queryDisplay = {}, Persist previewVideo = {},
              VideoSettings::Clock clock = {});
    MenuEvent update(const MenuInput& input, s32 ticks);
    /** Optional effects-volume demonstration generated by the latest update. */
    std::string_view audioSample() const { return m_audioSample; }
    void close();
    bool isOpen() const { return m_menu.isOpen(); }
    Page page() const { return m_page; }
    const GameConfig& config() const { return m_config; }
    const OptionMenu& menu() const { return m_menu; }
    OptionMenu& menu() { return m_menu; }
    void draw(Canvas& canvas, const TextPainter& painter, const MenuTextures& textures) const;

private:
    void rebuild(s32 selection = 0);
    void change(s32 direction);
    bool flushAudio();
    void commit(GameConfig next);
    std::string text(std::string_view id) const;
    OptionMenu m_menu;
    ControlSettings m_controls;
    MenuDefinition m_backdrop;
    const TextPainter* m_painter = nullptr;
    const StringTable* m_strings = nullptr;
    Persist m_persist;
    PreviewAudio m_previewAudio;
    DisplayOptions m_display;
    std::function<DisplayOptions()> m_queryDisplay;
    std::vector<Extent2D> resolutions() const;
    std::optional<usize> m_audioDrag;
    GameConfig m_config;
    std::string m_notice;
    VideoSettings m_video;
    Persist m_previewVideo;
    VideoSettings::Clock m_clock;
    s32 m_countdown = 0;
    MenuScreen m_screen;
    std::optional<Vec2> m_audioPointer;
    bool m_audioDirty = false;
    s32 m_audioSampleTicks = 0;
    bool m_audioSampleMagic = false;
    std::string_view m_audioSample;
    Scope m_scope = Scope::Title;
    Page m_page = Page::Root;
    bool m_confirmVideo = false;
};
} // namespace gdl::game
