# Keep the version accepted by CMake aligned with scripts/installer/versions.py.
# The complete SemVer string is used at runtime; project() needs its numeric core.
function(gdl_version_core version output)
    if(NOT "${version}" MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$")
        message(FATAL_ERROR "VERSION must be a semantic version, e.g. 0.1.0-alpha.1 or 1.0.0")
    endif()
    set(core "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
    set(prerelease "${CMAKE_MATCH_4}")
    if(prerelease)
        string(SUBSTRING "${prerelease}" 1 -1 prerelease)
        string(REPLACE "." ";" identifiers "${prerelease}")
        foreach(identifier IN LISTS identifiers)
            if("${identifier}" MATCHES "^0[0-9]+$")
                message(FATAL_ERROR "Numeric prerelease identifiers must not have leading zeros")
            endif()
        endforeach()
    endif()
    set(${output} "${core}" PARENT_SCOPE)
endfunction()
